### ISSUE TITLE
Basics Cheat Sheet

### ISSUE THREAD

**Issue by meganfitzsimons** [informatics-lab/pangeo-workshop#4]

**Comment by kaedonkers** [comment]
#13 Adds a cheatsheet for managing conda envs on panzure

**Comment by kaedonkers** [comment]
#14 Adds a PDF cheatsheet for Git + GitHub to supplement existing cheatsheet

**Comment by kaedonkers** [comment]
Looks good to me 👍

**Comment by meganfitzsimons** [comment]
Thanks for adding extras, looks good so going to close!
